kind: Deployment
metadata:
  name: java-webdeployment
spec:
  selector:
    matchLabels:
      app: java-webapp
  
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java-webapp
        image: sanmodi/test:latest
        ports:
        - containerPort: 8080
