apiVersion: v1
kind: Service
metadata:
  name: my-webservice
  labels:
    app: java-webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081  
      
  selector:
    app: java-webapp
